### ISSUE TITLE
[FEATURE] Add view in list format to home

### ISSUE THREAD

**Issue by shseok** [shseok/mztrees#19]
## Description
Users are viewing posts in the form of cards. To provide a diverse user experience, we plan to add a list format so that it can be viewed as a list.

## To-do
- [x] Add ViewSelector to the right end of TagSelector row
- [x] Applying query parameters as the view changes
- [ ] Adding a linklist component to be displayed as a list

## ETC
